import { db, stages, levels, userProgress } from "@workspace/db";

const stagesData = [
  {
    order: 1,
    nameAr: "أساسيات الشعر العربي",
    nameEn: "Arabic Poetry Foundations",
    descriptionAr: "ادخل عالم الشعر العربي من أوله — تعلم المصطلحات والأبيات والشعراء الأوائل",
    descriptionEn: "Enter the world of Arabic poetry from the beginning — learn the vocabulary, verses, and early poets",
    icon: "🌱",
    levelStart: 1,
    levelEnd: 20,
  },
  {
    order: 2,
    nameAr: "بحور الشعر",
    nameEn: "The Poetic Meters",
    descriptionAr: "اكتشف إيقاعات الشعر العربي — البحور الستة عشر التي تُنظّم موسيقى القصائد",
    descriptionEn: "Discover the rhythms of Arabic poetry — the sixteen meters that organize the music of verses",
    icon: "🥁",
    levelStart: 21,
    levelEnd: 40,
  },
  {
    order: 3,
    nameAr: "البلاغة والصور الشعرية",
    nameEn: "Rhetoric & Imagery",
    descriptionAr: "تعمّق في فن البيان — التشبيه والاستعارة والكناية وسائر الصور الأدبية",
    descriptionEn: "Dive into the art of expression — simile, metaphor, allusion, and literary devices",
    icon: "🎨",
    levelStart: 41,
    levelEnd: 60,
  },
  {
    order: 4,
    nameAr: "تحليل القصائد وتذوقها",
    nameEn: "Analysis & Appreciation",
    descriptionAr: "حلّل القصائد الكبرى وتذوّقها — من المعلقات إلى الشعر الحديث",
    descriptionEn: "Analyze and appreciate great poems — from the Mu'allaqat to modern poetry",
    icon: "🔍",
    levelStart: 61,
    levelEnd: 80,
  },
  {
    order: 5,
    nameAr: "الإنشاء والإبداع الشعري",
    nameEn: "Composition & Creativity",
    descriptionAr: "اكتب شعرك الخاص — من البيت الأول حتى القصيدة الكاملة",
    descriptionEn: "Write your own poetry — from the first verse to a complete poem",
    icon: "✍️",
    levelStart: 81,
    levelEnd: 100,
  },
];

const levelsData = [
  // STAGE 1: Foundations (1-20)
  { levelNumber: 1, nameAr: "ما هو الشعر؟", nameEn: "What is Poetry?", skillKey: "intro", skillDescriptionEn: "Understand what defines poetry vs prose and why Arabic poetry is unique", roleplaysScenarioAr: "أنت طالب جديد يجلس أمام المعلم في المدرسة العربية الكلاسيكية للمرة الأولى", roleplaysScenarioEn: "You are a new student sitting before the teacher in a classical Arabic school for the first time", systemPrompt: "You are Al-Mu'allim, beginning the student's first lesson. Warmly welcome them and introduce what poetry is — the difference between poetry (شعر) and prose (نثر), the basic unit of the verse (بيت), and why Arabs considered poetry the highest art form. Keep it simple, encouraging, and use one example. Ask them what they know or hope to learn.", xpReward: 50 },
  { levelNumber: 2, nameAr: "البيت والشطر", nameEn: "The Verse and Hemistich", skillKey: "verse_structure", skillDescriptionEn: "Learn that each verse (بيت) is made of two halves: the صدر and عجز", roleplaysScenarioAr: "أنت في حلقة دراسية حيث يقرأ المعلم بيتاً ويطلب منك أن تُحدّد شطريه", roleplaysScenarioEn: "You are in a study circle where the teacher reads a verse and asks you to identify its two halves", systemPrompt: "Teach the student that a verse (بيت) consists of a first hemistich (صدر) and second hemistich (عجز). Show this with a famous verse. Practice together by presenting 2-3 verses and asking them to identify the صدر and عجز. Praise correct answers and gently guide mistakes.", xpReward: 60 },
  { levelNumber: 3, nameAr: "القافية والروي", nameEn: "Rhyme and the Rhyme Letter", skillKey: "rhyme_basics", skillDescriptionEn: "Discover the rhyme system — قافية and the crucial روي (rhyme letter)", roleplaysScenarioAr: "أنت تساعد شاعراً يبحث عن كلمة تُتمّ قافية قصيدته — اقترح عليه!", roleplaysScenarioEn: "You are helping a poet who is searching for a word to complete his poem's rhyme — suggest one!", systemPrompt: "Teach the rhyme (قافية) system in Arabic poetry. The 'rawī' (روي) is the main rhyming letter that ends each verse. Show examples from famous poems. Play a game: give the student a rawī letter (like ر or ل or م) and ask them to think of words ending with it. Keep it playful and interactive.", xpReward: 60 },
  { levelNumber: 4, nameAr: "الشعراء الجاهليون", nameEn: "The Pre-Islamic Poets", skillKey: "poets_intro", skillDescriptionEn: "Meet the great poets of the pre-Islamic era — امرؤ القيس, طرفة, زهير", roleplaysScenarioAr: "أنت في سوق عكاظ — المهرجان الشعري الكبير — تستمع إلى الشعراء يتبارون", roleplaysScenarioEn: "You are at Souq Okaz — the great poetry festival — listening to poets compete", systemPrompt: "Take the student to the golden age of pre-Islamic (Jāhilī) poetry. Introduce the major poets: امرؤ القيس (the 'father of poetry'), طرفة بن العبد, زهير بن أبي سلمى, عنترة بن شداد, لبيد. Describe Souq Okaz as the ancient poetry festival. Share a memorable line from one of them and its meaning. Ask the student which poet intrigues them most.", xpReward: 70 },
  { levelNumber: 5, nameAr: "المعلقات السبع", nameEn: "The Seven Mu'allaqat", skillKey: "muallaqat", skillDescriptionEn: "Explore the legendary suspended poems — the seven masterpieces of pre-Islamic Arabic", roleplaysScenarioAr: "أنت تُشاهد إحدى المعلقات مكتوبةً بالذهب معلّقةً على أستار الكعبة", roleplaysScenarioEn: "You are witnessing one of the Mu'allaqat written in gold, suspended on the curtains of the Kaaba", systemPrompt: "Teach about the Mu'allaqat (المعلقات السبع) — the seven hanging odes considered the pinnacle of pre-Islamic poetry. Explain why they were called 'hanging' (suspended in gold on the Kaaba). Name all seven poets and their odes. Focus on one opening verse — the famous 'قفا نبكِ' by امرؤ القيس — and explain its imagery. Quiz the student on the poets' names.", xpReward: 80 },
  { levelNumber: 6, nameAr: "قفا نبكِ — تحليل أول بيت", nameEn: "The Iconic Opening Verse", skillKey: "verse_analysis_intro", skillDescriptionEn: "Deep-dive into the most famous opening in Arabic poetry: 'قفا نبكِ من ذِكرى حبيبٍ ومنزلِ'", roleplaysScenarioAr: "أنت امرؤ القيس تقف أمام الديار المهجورة، والمعلم يسألك عما تشعر به", roleplaysScenarioEn: "You ARE Imru' al-Qays standing before the abandoned campsite, and the teacher asks what you feel", systemPrompt: "Role-play: The student IS Imru' al-Qays. Describe the scene of the abandoned campsite (الديار). Analyze the verse 'قفا نبكِ من ذكرى حبيب ومنزلِ / بسِقطِ اللِّوى بين الدَّخُول فحَومَلِ'. Break down: the two companions he calls (قفا), the weeping, the memory, the beloved, the place names. Make it emotional and vivid.", xpReward: 80 },
  { levelNumber: 7, nameAr: "الشعر الإسلامي وصدر الإسلام", nameEn: "Islamic Era Poetry", skillKey: "islamic_era", skillDescriptionEn: "How poetry transformed with the dawn of Islam — Hassan ibn Thabit, Ka'b ibn Zuhayr", roleplaysScenarioAr: "أنت في المدينة المنورة تسمع حسّان بن ثابت يُنشد قصيدة في مدح النبي ﷺ", roleplaysScenarioEn: "You are in Medina listening to Hassan ibn Thabit recite a poem praising the Prophet ﷺ", systemPrompt: "Teach the transition of Arabic poetry in the Islamic era. Discuss: Hassan ibn Thabit (حسان بن ثابت) — 'the poet of the Prophet'; Ka'b ibn Zuhayr (كعب بن زهير) and his famous Burda poem. Explain how Islamic values shifted poetry themes. Share a famous line by Hassan and explain its meaning and historical context.", xpReward: 70 },
  { levelNumber: 8, nameAr: "شعر الغزل", nameEn: "Love Poetry — Al-Ghazal", skillKey: "ghazal", skillDescriptionEn: "Learn the art of love poetry — the Udhri tradition and the sensual Hijazi school", roleplaysScenarioAr: "أنت شاعر أموي يُخاطب حبيبته التي أحبها ولم ينلها — اكتب لها سطراً", roleplaysScenarioEn: "You are an Umayyad poet addressing your beloved whom you love but cannot reach — write her a line", systemPrompt: "Explore Arabic love poetry (الغزل). Contrast two schools: the 'Udhri' (العذري) — chaste, spiritual love where the lover pines without union (like Qays 'Majnun Layla'); and the 'Hijazi' or sensual school (like Omar ibn Abi Rabia — عمر بن أبي ربيعة). Share famous examples. Ask the student to try writing one line expressing longing in Arabic or English, then help them refine it.", xpReward: 90 },
  { levelNumber: 9, nameAr: "شعر الفخر والحماسة", nameEn: "Boast and Warrior Poetry", skillKey: "fakhr_hamasa", skillDescriptionEn: "Experience the fierce pride and bravery in Arabic warrior poetry", roleplaysScenarioAr: "أنت عنترة بن شداد في ميدان المعركة تُنشد بيتاً يُرهب أعداءك", roleplaysScenarioEn: "You ARE Antarah ibn Shaddad on the battlefield, reciting a verse to terrify your enemies", systemPrompt: "Role-play: The student IS Antarah ibn Shaddad — the legendary warrior-poet. Teach the tradition of فخر (boasting) and حماسة (martial valor) in Arabic poetry. Share the famous verse: 'وإنّي لأثني الطعنة الشزرَ بعدَها / طعاناً كإيماء الأيادي إلى السرّ'. Discuss the themes: tribal pride, courage, protecting the beloved. Ask the student to improvise a boastful line about their own strengths.", xpReward: 90 },
  { levelNumber: 10, nameAr: "شعر الرثاء", nameEn: "Elegy — Poetry of Grief", skillKey: "ritha", skillDescriptionEn: "Learn the deeply emotional tradition of Arabic elegies — mourning through poetry", roleplaysScenarioAr: "أنت الخنساء — أعظم شاعرة العرب — ترثي أخاك صخراً الذي سقط في المعركة", roleplaysScenarioEn: "You ARE Al-Khansa — the greatest Arab poetess — mourning your brother Sakhr who fell in battle", systemPrompt: "Role-play: The student IS Al-Khansa (الخنساء) — the greatest Arab poetess, famous for her elegies. Teach the elegy (رثاء) tradition. Share her famous verse: 'وإنّ صخراً لتأتمّ الهداةُ به / كأنّه عَلَمٌ في رأسِه نارُ'. Discuss how elegy (رثاء) became one of the highest forms of Arabic poetry. Explore the themes of loss, honor, and immortalizing the dead through verse.", xpReward: 90 },
  { levelNumber: 11, nameAr: "شعر الهجاء", nameEn: "Satire Poetry", skillKey: "hija", skillDescriptionEn: "Discover the biting wit of Arabic satirical poetry — a weapon of words", roleplaysScenarioAr: "أنت شاعر أموي تُواجه منافسك جريراً في دار الخليفة — كلٌّ منكما يرد على الآخر", roleplaysScenarioEn: "You are an Umayyad poet facing your rival Jarir in the Caliph's court — each responding to the other", systemPrompt: "Teach the tradition of هجاء (satirical poetry) in Arabic — one of the most entertaining and feared forms. Tell the story of the great rivalry between جرير (Jarir) and الفرزدق (Al-Farazdaq) and their legendary poetic battles النقائض (naqāʾiḍ). Share a witty satirical verse. Role-play: the student and teacher engage in a playful, respectful mock-poetic exchange.", xpReward: 80 },
  { levelNumber: 12, nameAr: "المتنبي — أعظم شعراء العربية", nameEn: "Al-Mutanabbi — The Greatest", skillKey: "mutanabbi", skillDescriptionEn: "Study the legendary Al-Mutanabbi — the most quoted and celebrated Arab poet", roleplaysScenarioAr: "أنت في بلاط سيف الدولة الحمداني في حلب — والمتنبي يُنشد قصيدته الجديدة لأول مرة", roleplaysScenarioEn: "You are in the court of Sayf al-Dawla in Aleppo — Al-Mutanabbi is reciting his new poem for the first time", systemPrompt: "Introduce Al-Mutanabbi (أبو الطيب المتنبي) — the undisputed king of Arabic poetry. His life story: from claiming prophethood (hence 'Mutanabbi') to the court of Sayf al-Dawla. Teach his most famous verses and their meanings: 'على قدرِ أهلِ العزمِ تأتي العزائمُ', 'الخيلُ والليلُ والبيداءُ تعرفُني'. Role-play the student as a courtier hearing him for the first time.", xpReward: 100 },
  { levelNumber: 13, nameAr: "أبو نواس — شاعر الخمر والمجون", nameEn: "Abu Nuwas — The Rebel Poet", skillKey: "abu_nuwas", skillDescriptionEn: "Explore the irreverent genius of Abu Nuwas and his unconventional poetry", roleplaysScenarioAr: "أنت في مجلس هارون الرشيد في بغداد — أبو نواس يُلقي أمامك قصيدته المثيرة للجدل", roleplaysScenarioEn: "You are in Harun al-Rashid's salon in Baghdad — Abu Nuwas is reciting his controversial poem before you", systemPrompt: "Introduce Abu Nuwas (أبو نواس) — the brilliant, rebellious poet of Abbasid Baghdad. Explain his famous khamriyyat (خمريات — wine poems) as a complex literary and philosophical genre. Discuss how he challenged the old Bedouin traditions and invented new forms. Share a famous verse. Contextualize him as a product of cosmopolitan Baghdad and explain why his poetry still resonates.", xpReward: 80 },
  { levelNumber: 14, nameAr: "أبو العلاء المعري — الشاعر الفيلسوف", nameEn: "Al-Ma'arri — The Philosopher Poet", skillKey: "maari", skillDescriptionEn: "Encounter the blind, vegetarian, philosophical genius Al-Ma'arri", roleplaysScenarioAr: "أنت زائر لشاعر أعمى في معرّة النعمان — يُلقّن الشعر من الظلام إلى النور", roleplaysScenarioEn: "You visit a blind poet in Ma'arrat al-Nu'man — he teaches poetry from darkness into light", systemPrompt: "Introduce Abu al-Ala al-Ma'arri (أبو العلاء المعري) — the blind philosopher-poet who rejected dogma and meat. His famous 'Luzumiyyat' with double-constrained rhymes. Teach his famous skeptical verse: 'وإنّما أولادُنا بيننا / أكبادُنا تمشي على الأرضِ'. Role-play: the student visits his house and asks him a philosophical question about life and poetry.", xpReward: 90 },
  { levelNumber: 15, nameAr: "الشعر الأندلسي", nameEn: "Andalusian Poetry", skillKey: "andalusian", skillDescriptionEn: "Discover the golden age of Arabic poetry in Islamic Spain — Ibn Zaydun, Wallada", roleplaysScenarioAr: "أنت في حدائق قصر الحمراء في غرناطة — شاعران يتبادلان قصائد الحب", roleplaysScenarioEn: "You are in the gardens of Alhambra in Granada — two poets exchange love poems", systemPrompt: "Transport the student to Andalusia (الأندلس) — Islamic Spain — one of the most fertile eras for Arabic poetry. Introduce: Ibn Zaydun (ابن زيدون) and his legendary love for the princess Wallada; Ibn Khafaja (ابن خفاجة) and his nature poetry. Teach the Muwashshah (الموشّح) — the new Andalusian strophic form invented as an alternative to the classic qasida. Share the famous verse of Ibn Zaydun: 'أضحى التنائي بديلاً من تدانينا'.", xpReward: 90 },
  { levelNumber: 16, nameAr: "محمود درويش — شاعر فلسطين", nameEn: "Mahmoud Darwish — Poet of Palestine", skillKey: "darwish", skillDescriptionEn: "Encounter the most celebrated modern Arabic poet and his poetry of exile", roleplaysScenarioAr: "أنت تستمع إلى درويش يُلقي قصيدته 'على هذه الأرض ما يستحق الحياة' في أمسية شعرية", roleplaysScenarioEn: "You listen to Darwish recite 'On This Earth What Makes Life Worth Living' at a poetry evening", systemPrompt: "Introduce Mahmoud Darwish (محمود درويش) — the greatest modern Arabic poet and the voice of Palestinian identity. Teach his famous poem 'على هذه الأرض ما يستحق الحياة' and the iconic 'سجّل أنا عربي' (Record, I am an Arab). Discuss his themes: exile, memory, land, love, and identity. Role-play: student attends one of his legendary poetry readings.", xpReward: 100 },
  { levelNumber: 17, nameAr: "نزار قباني — شاعر المرأة", nameEn: "Nizar Qabbani — Poet of Women", skillKey: "qabbani", skillDescriptionEn: "Explore Nizar Qabbani's revolutionary, sensual, and political love poetry", roleplaysScenarioAr: "أنت تقرأ رسالة مكتوبة بالشعر من نزار قباني إلى امرأة يحبها — ردّ عليه بشطر!", roleplaysScenarioEn: "You read a poetic letter from Nizar Qabbani to a woman he loves — respond with a line!", systemPrompt: "Introduce Nizar Qabbani (نزار قباني) — the poet who revolutionized Arabic love poetry. Discuss how he wrote accessibly, sensually, and politically. Teach his famous verses: from love poems to 'متى يُعلنون وفاة العرب' after 1967. Role-play: the student receives a 'poetic letter' from Qabbani and must respond with a line. Guide them to express emotion simply and beautifully.", xpReward: 90 },
  { levelNumber: 18, nameAr: "أدونيس والشعر الحر", nameEn: "Adonis and Free Verse", skillKey: "free_verse", skillDescriptionEn: "The modernist revolution — how Adonis broke classical rules and invented new Arabic poetry", roleplaysScenarioAr: "أنت في مؤتمر شعري — نصف الشعراء يدافعون عن الشعر الكلاسيكي والنصف الآخر عن الحر", roleplaysScenarioEn: "You are at a poetry conference — half the poets defend classical forms, half defend free verse — which side are you on?", systemPrompt: "Introduce the modernist revolution in Arabic poetry. Teach Adonis (أدونيس — علي أحمد سعيد) and Badr Shakir al-Sayyab (بدر شاكر السياب) — pioneers of free verse (شعر حر / التفعيلة). Contrast classical قصيدة with modern free verse. Role-play a debate: the student argues for one side while the teacher argues the other. Ultimately, show how both forms are valuable.", xpReward: 100 },
  { levelNumber: 19, nameAr: "قصيدة النثر", nameEn: "The Prose Poem", skillKey: "prose_poem", skillDescriptionEn: "The most radical form — when poetry abandons meter and rhyme entirely", roleplaysScenarioAr: "أنت تكتب في دفترك صباحاً بلا قواعد — كل ما تشعر به هو شعر", roleplaysScenarioEn: "You write in your notebook in the morning with no rules — everything you feel is poetry", systemPrompt: "Introduce قصيدة النثر (the prose poem) — poetry without meter or rhyme, relying purely on imagery, rhythm of thought, and emotional intensity. Discuss how controversial it was (and still is). Read an example together. Guide the student to write their own short prose poem about anything — a feeling, a memory, an image. Celebrate whatever they create as a genuine poem.", xpReward: 80 },
  { levelNumber: 20, nameAr: "اختبار المرحلة الأولى", nameEn: "Stage 1 Final Challenge", skillKey: "stage1_review", skillDescriptionEn: "Test everything from Stage 1 — poets, terms, verse structure, and your first attempt at writing", roleplaysScenarioAr: "أنت أمام لجنة من الشعراء العظماء — المتنبي وامرؤ القيس ودرويش — يسألونك عن رحلتك", roleplaysScenarioEn: "You stand before a panel of great poets — Al-Mutanabbi, Imru' al-Qays, and Darwish — they quiz you on your journey", systemPrompt: "This is the Stage 1 review session. Role-play: The student stands before a panel of three great poets — Al-Mutanabbi, Imru' al-Qays, and Mahmoud Darwish — who quiz them on everything learned so far. Ask 5 questions covering: verse structure, rhyme, one poet biography, a famous verse, and a personal reflection. At the end, congratulate the student and encourage them to advance to Stage 2 — The Meters.", xpReward: 150 },

  // STAGE 2: The Meters (21-40)
  { levelNumber: 21, nameAr: "ما هي البحور؟", nameEn: "What are the Meters?", skillKey: "meters_intro", skillDescriptionEn: "Introduction to Arabic prosody — 'Ilm al-'Arud — and the concept of taf'ila", roleplaysScenarioAr: "أنت تجلس مع الخليل بن أحمد الفراهيدي — مكتشف البحور — في بصرة القرن الثامن", roleplaysScenarioEn: "You sit with Al-Khalil ibn Ahmad al-Farahidi — discoverer of the meters — in 8th-century Basra", systemPrompt: "Introduce 'Ilm al-'Arud (علم العروض) — Arabic prosody. Explain Al-Khalil ibn Ahmad al-Farahidi who discovered and codified the 16 meters. Introduce the concept of تفعيلة (taf'ila — the metrical foot). Explain the two building blocks: the سبب (two-letter unit) and الوتد (three-letter unit). Make it accessible with a clapping/rhythm exercise. Keep the tone encouraging — meter can seem complex at first.", xpReward: 100 },
  { levelNumber: 22, nameAr: "بحر الطويل", nameEn: "Al-Tawil — The Long Meter", skillKey: "meter_tawil", skillDescriptionEn: "Master the most used meter in classical Arabic poetry — فعولن مفاعيلن × 4", roleplaysScenarioAr: "أنت ترافق كاتباً في مكتبة بغداد — يقرأ بصوت عالٍ بيتاً بالطويل ويطلب منك تكراره", roleplaysScenarioEn: "You accompany a scholar in Baghdad's library — he reads aloud a verse in Al-Tawil and asks you to repeat it", systemPrompt: "Teach Bahr al-Tawil (بحر الطويل) — the most common meter in classical Arabic poetry. Pattern: فعولن مفاعيلن فعولن مفاعيلن. Clap or hum the rhythm together. Give the student famous verses in this meter (like امرؤ القيس's Mu'allaqa opener). Practice identifying the meter in 2-3 verses. Ask the student to clap along as you read a verse aloud.", xpReward: 110 },
  { levelNumber: 23, nameAr: "بحر البسيط", nameEn: "Al-Basit — The Simple Meter", skillKey: "meter_basit", skillDescriptionEn: "Learn the elegant Al-Basit meter — مستفعلن فاعلن × 4", roleplaysScenarioAr: "أنت شاعر أموي تختار بحر البسيط لقصيدة حكمة — المعلم يُصفّق مع إيقاعك", roleplaysScenarioEn: "You are an Umayyad poet choosing Al-Basit meter for a wisdom poem — the teacher claps with your rhythm", systemPrompt: "Teach Bahr al-Basit (بحر البسيط). Pattern: مستفعلن فاعلن مستفعلن فاعلن. Distinguish it from al-Tawil by its feel. Give examples. Practice with famous verses including from Abu Nuwas. Have the student count syllables and tap the rhythm. Quiz: present a verse and ask if it's Tawil or Basit.", xpReward: 110 },
  { levelNumber: 24, nameAr: "بحر الكامل", nameEn: "Al-Kamil — The Perfect Meter", skillKey: "meter_kamil", skillDescriptionEn: "Learn the 'perfect' meter beloved by المتنبي — متفاعلن × 6", roleplaysScenarioAr: "أنت تسمع المتنبي ينشد قصيدته الحماسية على بحر الكامل — تشعر بالإيقاع في صدرك", roleplaysScenarioEn: "You listen to Al-Mutanabbi recite his martial poem in Al-Kamil — you feel the rhythm in your chest", systemPrompt: "Teach Bahr al-Kamil (بحر الكامل) — the 'perfect' meter, one of the most musical. Pattern: متفاعلن متفاعلن متفاعلن. Al-Mutanabbi loved this meter. Teach the famous verse 'على قدرِ أهلِ العزمِ تأتي العزائمُ' — tap out the rhythm together. Practice distinguishing Kamil from Tawil. Quiz the student with 3 verses to identify.", xpReward: 110 },
  { levelNumber: 25, nameAr: "بحر الوافر", nameEn: "Al-Wafir — The Abundant Meter", skillKey: "meter_wafir", skillDescriptionEn: "The flowing abundant meter — مفاعلتن × 3 per hemistich", roleplaysScenarioAr: "أنت على ظهر جمل في الصحراء والإيقاع الهادئ للوافر يُناسب رحلتك الطويلة", roleplaysScenarioEn: "You are on a camel in the desert and the gentle rhythm of Al-Wafir suits your long journey", systemPrompt: "Teach Bahr al-Wafir (بحر الوافر). It has a rolling, abundant feel — مفاعلتن مفاعلتن مفاعل. Perfect for elegies and reflective poetry. Give examples. Practice the rhythm by imagining the sway of a camel. Quiz: distinguish Wafir from Kamil with sample verses.", xpReward: 110 },
  { levelNumber: 26, nameAr: "بحر الهزج", nameEn: "Al-Hazaj — The Light, Joyful Meter", skillKey: "meter_hazaj", skillDescriptionEn: "The lightest, most musical meter — مفاعيلن × 2, often used in song", roleplaysScenarioAr: "أنت في حفل موسيقي عربي والموسيقيون يُغنّون على بحر الهزج الرشيق", roleplaysScenarioEn: "You are at an Arab music gathering and the musicians sing in the light, dancing Al-Hazaj meter", systemPrompt: "Teach Bahr al-Hazaj (بحر الهزج) — the lightest, most musical meter, often used for songs and light verse. Pattern: مفاعيلن مفاعيلن. Give examples of classic poems and songs in this meter. Practice clapping the cheerful rhythm. Explain how music and poetry were inseparable in classical Arab culture.", xpReward: 100 },
  { levelNumber: 27, nameAr: "بحر الرجز", nameEn: "Al-Rajaz — The Camel Driver's Meter", skillKey: "meter_rajaz", skillDescriptionEn: "The ancient Rajaz meter — مستفعلن × 3 — used by camel drivers and then elevated to art", roleplaysScenarioAr: "أنت حادي الإبل في قافلة — تُنشد رجزاً يحثّ الإبل على السير", roleplaysScenarioEn: "You are a camel driver in a caravan — chanting Rajaz to urge the camels forward", systemPrompt: "Teach Bahr al-Rajaz (بحر الرجز) — the ancient meter of camel drivers that became a sophisticated art. Pattern: مستفعلن مستفعلن مستفعلن. Role-play: the student IS a camel driver, and the teacher shows them how to compose urging chants (حُداء). Discuss how Rajaz was later elevated by scholars like Ibn Malik in his famous Alfiyya poem. Make it fun and physical.", xpReward: 100 },
  { levelNumber: 28, nameAr: "بحر الرمل", nameEn: "Al-Ramal — The Sand Meter", skillKey: "meter_ramal", skillDescriptionEn: "The gentle, flowing Ramal meter — فاعلاتن × 3 per hemistich", roleplaysScenarioAr: "أنت شاعر أندلسي يكتب على ضفاف نهر الوادي الكبير — الإيقاع الرقيق يُناسب المكان", roleplaysScenarioEn: "You are an Andalusian poet writing on the banks of the Guadalquivir — the gentle rhythm suits the setting", systemPrompt: "Teach Bahr al-Ramal (بحر الرمل). Pattern: فاعلاتن فاعلاتن فاعلن. Give examples from Andalusian and Abbasid poetry. Practice the pattern. Discuss why gentle meters suit gentle emotions (nature, love, reflection). Quiz: identify Ramal vs. Hazaj in sample verses.", xpReward: 110 },
  { levelNumber: 29, nameAr: "بحر السريع", nameEn: "Al-Sari' — The Swift Meter", skillKey: "meter_sari", skillDescriptionEn: "The quickest and most energetic meter — مستفعلن مستفعلن مفعولاتُ", roleplaysScenarioAr: "أنت في ميدان الفروسية والشعراء يُنشدون أبيات الحماسة السريعة لإشعال الحمية", roleplaysScenarioEn: "You are at a jousting ground and poets recite swift verses to fire up the warriors", systemPrompt: "Teach Bahr al-Sari' (بحر السريع) — the 'swift' meter, often used for energetic, martial, or satirical poetry. Pattern: مستفعلن مستفعلن مفعولاتُ. Clap the fast rhythm together. Give examples of poems in this meter that capture urgency or excitement. Quiz: tap out Sari' vs. Rajaz.", xpReward: 110 },
  { levelNumber: 30, nameAr: "بحر الخفيف", nameEn: "Al-Khafif — The Light Meter", skillKey: "meter_khafif", skillDescriptionEn: "One of the most versatile meters — فاعلاتن مستفعلن فاعلاتن", roleplaysScenarioAr: "أنت شاعر تُفكّر في ما تُريد قوله — وبحر الخفيف يُعطيك المرونة للتعبير", roleplaysScenarioEn: "You are a poet thinking about what you want to say — Al-Khafif gives you the flexibility to express it", systemPrompt: "Teach Bahr al-Khafif (بحر الخفيف). Pattern: فاعلاتن مستفعلن فاعلاتن. Discuss how its mixed feet make it exceptionally versatile for many themes. Give examples from diverse poets. Practice clapping. Quiz: can the student match the last 4 meters they've learned to sample verses?", xpReward: 110 },
  { levelNumber: 31, nameAr: "البحور المتبقية", nameEn: "The Remaining Meters Overview", skillKey: "meters_remaining", skillDescriptionEn: "Survey of المنسرح, المضارع, المقتضب, المجتث, المتقارب, المتدارك, والمديد", roleplaysScenarioAr: "أنت تتصفّح كتاب العروض في مكتبة الخليل — كل صفحة تكشف بحراً جديداً", roleplaysScenarioEn: "You browse through Al-Khalil's prosody book in his library — each page reveals a new meter", systemPrompt: "Survey the remaining meters: المنسرح (al-Munsarih), المضارع (al-Mudari'), المقتضب (al-Muqtadab), المجتث (al-Mujtath), المتقارب (al-Mutaqarib — فعولن × 4), المتدارك (al-Mutadarak), والمديد (al-Madid). Give a one-line example for each. Focus on المتقارب as it's the most used of this group. Quiz: match descriptions to meter names.", xpReward: 120 },
  { levelNumber: 32, nameAr: "الزحافات والعلل", nameEn: "Metrical Variations", skillKey: "zihaf_illa", skillDescriptionEn: "Learn how poets modify feet with zihaf (minor changes) and 'illa (major changes)", roleplaysScenarioAr: "أنت ناقد أدبي يفحص قصيدة للتحقق من صحة بحرها ومعرفة تحويلاتها", roleplaysScenarioEn: "You are a literary critic examining a poem to verify its meter and identify its variations", systemPrompt: "Introduce زحافات (zihaf — minor metrical variations) and علل ('ilal — major metrical variations) that allow poets to modify feet within accepted rules. This is what makes each verse feel slightly different even in the same meter. Show examples of الخبن (removing the 2nd letter of a foot) and الطي (removing the 4th letter). Keep it practical with examples rather than overwhelming theory.", xpReward: 130 },
  { levelNumber: 33, nameAr: "تمييز البحور سماعياً", nameEn: "Identifying Meters by Ear", skillKey: "meter_identification", skillDescriptionEn: "Train your ear to identify meters by rhythm alone — the poet's musical skill", roleplaysScenarioAr: "أنت في اختبار شفهي — المعلم يُنشد أبياتاً وعليك تسمية البحر", roleplaysScenarioEn: "You are in an oral exam — the teacher recites verses and you must name the meter", systemPrompt: "Oral drill: Present 8 famous verses one by one. For each, give the student a moment to identify the meter. Reveal the answer and explain the tell-tale pattern. Cover: Tawil, Basit, Kamil, Wafir, Ramal, Khafif, Rajaz, Mutaqarib. Encourage the student to hum the pattern aloud. By the end, test: can they identify any meter when they hear it?", xpReward: 140 },
  { levelNumber: 34, nameAr: "القوافي المركبة", nameEn: "Complex Rhyme Schemes", skillKey: "advanced_rhyme", skillDescriptionEn: "Go beyond simple end rhyme — explore redif, tajnis, and rhyme variations", roleplaysScenarioAr: "أنت تحكّم مسابقة شعرية — الشعراء يتنافسون بقوافٍ صعبة ومُركّبة", roleplaysScenarioEn: "You are judging a poetry competition — poets compete with complex and difficult rhyme schemes", systemPrompt: "Teach advanced rhyme concepts: الردف (radif — a repeated word or phrase after the rawī), التجنيس (tajnis — homophonic rhyme), والتصريع (tasri' — rhyming the two halves of the first verse). Give examples. Role-play: judge a poetry competition where the student evaluates which poet has the most sophisticated rhyme scheme.", xpReward: 130 },
  { levelNumber: 35, nameAr: "الموشّح الأندلسي", nameEn: "The Andalusian Muwashshah", skillKey: "muwashshah", skillDescriptionEn: "The strophic poem form invented in Andalusia — a departure from the monorrhyme qasida", roleplaysScenarioAr: "أنت في حديقة أندلسية — موسيقيون يُغنّون موشّحاً بينما تتساقط أوراق الخريف", roleplaysScenarioEn: "You are in an Andalusian garden — musicians sing a Muwashshah as autumn leaves fall", systemPrompt: "Teach the Muwashshah (الموشّح) — the strophic form invented in al-Andalus as an alternative to the classic monorhyme qasida. It has multiple stanzas with changing rhymes and a closing kharja (خرجة — often in Romance language or colloquial Arabic). Analyze a famous muwashshah together. The student composes a short 2-stanza muwashshah on any theme.", xpReward: 140 },
  { levelNumber: 36, nameAr: "الدوبيت والقطعة", nameEn: "Short Forms — Dobeyt and Qit'a", skillKey: "short_forms", skillDescriptionEn: "Explore the short poetic forms — the two-line Dobeyt and the multi-verse Qit'a", roleplaysScenarioAr: "أنت تكتب على بطاقة صغيرة حكمةً في بيتين — مثل الرسائل التي يُرسلها الشعراء لبعضهم", roleplaysScenarioEn: "You write a wisdom thought in two verses on a small card — like the letters poets used to send each other", systemPrompt: "Teach shorter poetic forms: the دوبيت (dobeyt — two verses, usually epigrammatic) and the قطعة (qit'a — a fragment or section, shorter than a full qasida but complete in itself). These forms allowed poets to be witty and concise. Give examples of epigrammatic wisdom verses. Ask the student to compose a two-line poem expressing a personal truth or observation.", xpReward: 120 },
  { levelNumber: 37, nameAr: "الشعر الشعبي والزجل", nameEn: "Folk Poetry and Zajal", skillKey: "zajal", skillDescriptionEn: "Poetry of the people — the Zajal tradition in colloquial Arabic dialects", roleplaysScenarioAr: "أنت في سهرة شعبية — شاعران يتبادلان أبيات الزجل ارتجالاً والجمهور يُصفّق", roleplaysScenarioEn: "You are at a folk evening — two poets improvise Zajal verses back and forth while the crowd claps", systemPrompt: "Introduce الزجل (zajal) — folk poetry composed in colloquial Arabic dialects (not classical fusha). This was the poetry of ordinary people. Discuss the Lebanese zajal tradition (شعر عامّي) and its masters. Contrast it with classical poetry without dismissing it — zajal is a legitimate, rich art form. Role-play: the teacher and student improvise a short zajal exchange on a simple topic.", xpReward: 110 },
  { levelNumber: 38, nameAr: "الشعر العمودي مقابل التفعيلة", nameEn: "Classical vs. Free Verse — A Deeper Look", skillKey: "classical_vs_free", skillDescriptionEn: "Understand the technical difference between classical عمودي poetry and modern التفعيلة", roleplaysScenarioAr: "أنت تحضر ندوة حيث الخليل بن أحمد والسياب يناقشان أشكال الشعر", roleplaysScenarioEn: "You attend a seminar where Al-Khalil ibn Ahmad and Al-Sayyab debate poetic forms", systemPrompt: "Deep dive into the structural differences: الشعر العمودي (classical — monorhyme, strict meter, each verse = complete unit) vs. شعر التفعيلة (modern free verse — uses taf'ila as unit but irregular length, no monorhyme). Compare a classical Al-Mutanabbi verse to a Darwish poem. Imaginary debate: Al-Khalil defends classical, Al-Sayyab defends free verse. The student decides which side convinces them more.", xpReward: 130 },
  { levelNumber: 39, nameAr: "وزن الشعر يدوياً", nameEn: "Manual Scansion Practice", skillKey: "scansion", skillDescriptionEn: "Learn to scan a verse — mark syllables as long/short and identify the taf'ila pattern", roleplaysScenarioAr: "أنت تعمل على مخطوطة قديمة — تحاول تحديد وزن قصيدة لم يُعرف بحرها", roleplaysScenarioEn: "You work on an ancient manuscript — trying to determine the meter of an unidentified poem", systemPrompt: "Teach manual scansion (التقطيع العروضي) — the process of marking each syllable as long (/) or short (u) and identifying the taf'ila pattern. Practice with 3 verses step by step. Explain the notation system. Give the student one verse to scan themselves, then check their work together. This is the most technical level — be patient and methodical.", xpReward: 150 },
  { levelNumber: 40, nameAr: "اختبار المرحلة الثانية", nameEn: "Stage 2 Final Challenge", skillKey: "stage2_review", skillDescriptionEn: "Master test on all the meters, scansion, and advanced rhyme concepts", roleplaysScenarioAr: "أنت أمام الخليل بن أحمد نفسه — يُمتحنك في علم العروض الذي اخترعه", roleplaysScenarioEn: "You stand before Al-Khalil ibn Ahmad himself — he examines you in the science of prosody he invented", systemPrompt: "Final Stage 2 exam. Role-play: The student stands before Al-Khalil ibn Ahmad al-Farahidi. He asks: (1) Name 6 meters; (2) Identify the meter in this verse [give one]; (3) What is zihaf?; (4) What is the difference between Tawil and Basit?; (5) Scan this half-verse. Grade each answer, celebrate what was learned, and congratulate them for completing Stage 2 — The Meters.", xpReward: 200 },

  // STAGE 3: Rhetoric (41-60)
  { levelNumber: 41, nameAr: "مقدمة في علم البيان", nameEn: "Introduction to Arabic Rhetoric", skillKey: "rhetoric_intro", skillDescriptionEn: "Overview of the three branches of Arabic rhetoric: البيان، المعاني، البديع", roleplaysScenarioAr: "أنت تدخل حلقة علم البيان في الجامعة النظامية ببغداد", roleplaysScenarioEn: "You enter the rhetoric study circle at the Nizamiyya in Baghdad", systemPrompt: "Introduce Arabic rhetoric (البلاغة) — the three sciences: 1) علم البيان (figurative language — simile, metaphor, etc.), 2) علم المعاني (meaning/syntax — how word order creates meaning), 3) علم البديع (ornamentation — wordplay, antithesis, etc.). Frame these as the tools a poet uses to move hearts. Motivate the student by saying mastery of these makes one truly read poetry, not just hear it.", xpReward: 100 },
  { levelNumber: 42, nameAr: "التشبيه", nameEn: "The Simile — Al-Tashbih", skillKey: "tashbih", skillDescriptionEn: "Master the four elements of the Arabic simile and its types", roleplaysScenarioAr: "أنت شاعر تصف ليلة مقمرة — المعلم يُطلب منك تشبيه القمر بشيء لم يُشبَّه به من قبل", roleplaysScenarioEn: "You are a poet describing a moonlit night — the teacher challenges you to compare the moon to something never compared before", systemPrompt: "Teach the simile (التشبيه) in Arabic poetry: its four elements — المشبَّه (subject), المشبَّه به (comparison), أداة التشبيه (like/as), and وجه الشبه (the point of similarity). Types: التشبيه البليغ (elliptical — dropping the tool), التمثيل (complex simile). Give 5 poetic examples. Challenge: the student must create 3 original similes, one simple, one elliptical.", xpReward: 110 },
  { levelNumber: 43, nameAr: "الاستعارة", nameEn: "The Metaphor — Al-Isti'ara", skillKey: "istara", skillDescriptionEn: "The highest figurative device — metaphor where the simile elements collapse into one", roleplaysScenarioAr: "المعلم يُعطيك جملة بها استعارة مكنية — عليك أن تكشف ما اختبأ فيها", roleplaysScenarioEn: "The teacher gives you a sentence with a hidden metaphor — you must reveal what is concealed inside it", systemPrompt: "Teach the metaphor (الاستعارة) — when one thing IS declared to be another. Types: استعارة تصريحية (explicit — the comparison object replaces the subject); استعارة مكنية (implicit — the comparison is hidden, only its attributes appear). Famous example: 'المنيّة أنشبت أظفارها' (Death sank its claws) — death is implicitly compared to a beast without saying so. Practice identifying both types in verses.", xpReward: 120 },
  { levelNumber: 44, nameAr: "الكناية", nameEn: "Al-Kinaya — The Allusion", skillKey: "kinaya", skillDescriptionEn: "Poetry that speaks of one thing to mean another — the art of elegant indirection", roleplaysScenarioAr: "أنت في مجلس ملكي — لا يمكنك قول الحقيقة مباشرة، لكن بالكناية تقول كل شيء", roleplaysScenarioEn: "You are in a royal court — you cannot say the truth directly, but through kinaya you say everything", systemPrompt: "Teach الكناية (kinaya — metonymy/allusion) — when a poet says X to mean Y. Example: saying 'long sword' to mean 'noble' (طويل النجاد). Three types of kinaya: عن صفة (quality), عن موصوف (a person/thing), عن نسبة (a relationship). Role-play: the student must express 3 qualities — generosity, courage, beauty — without naming them directly, using kinaya.", xpReward: 120 },
  { levelNumber: 45, nameAr: "المجاز المرسل", nameEn: "Al-Majaz al-Mursal — Metonymy", skillKey: "majaz", skillDescriptionEn: "When a word is used for something related to its original meaning — the 7 types of metonymy", roleplaysScenarioAr: "أنت تقرأ قصيدة وتجد كلمة في غير معناها الأصلي — ابحث عن العلاقة!", roleplaysScenarioEn: "You read a poem and find a word used outside its literal meaning — find the relationship!", systemPrompt: "Teach المجاز المرسل (metonymy) — using a word for something related but not identical. Examples of the relations: the part for the whole (الجزء عن الكل), the cause for the effect, the place for its inhabitants. Classic example: 'وأشربوا في قلوبهم العجل' (Quran) — they drank the calf = they absorbed love of the calf. Practice identifying the type of relationship in 5 examples.", xpReward: 120 },
  { levelNumber: 46, nameAr: "الطباق والمقابلة", nameEn: "Antithesis — Al-Tiba' and Al-Muqabala", skillKey: "tibaq", skillDescriptionEn: "The power of opposites — pairing contrasting words or ideas for dramatic effect", roleplaysScenarioAr: "أنت تكتب بيتاً وتريد أن يكون ذا أثر قوي — المعلم يُوصيك بالطباق", roleplaysScenarioEn: "You want to write a verse with maximum impact — the teacher advises you to use antithesis", systemPrompt: "Teach الطباق (tibaq — antithesis: pairing opposites in the same verse) and المقابلة (muqabala — parallel antithesis with multiple pairs). Famous example: 'تبيضّ الوجوه وتسودّ وجوه' — faces whiten (joy/success) while faces blacken (shame/failure). Al-Mutanabbi was a master of tibaq. Give 5 examples. Ask the student to write a verse using tibaq of their own.", xpReward: 120 },
  { levelNumber: 47, nameAr: "الجناس", nameEn: "Al-Jinas — Paronomasia", skillKey: "jinas", skillDescriptionEn: "The art of wordplay — words that sound alike but mean different things", roleplaysScenarioAr: "أنت في مسابقة البلاغة — المحكّم يطلب منك بيتاً فيه جناس محكم", roleplaysScenarioEn: "You are in a rhetoric competition — the judge asks you for a verse with masterful wordplay", systemPrompt: "Teach الجناس (jinas — paronomasia/wordplay). Types: الجناس التام (perfect: same pronunciation/letters, different meaning) and الجناس الناقص (imperfect: near-similar sounds). Famous example of perfect jinas: 'ويُتمتعون إذا تمتّعوا' / comparing verbs that look and sound identical but have different meanings in different roots. Challenge: the student tries to find or create a simple wordplay in Arabic or English.", xpReward: 130 },
  { levelNumber: 48, nameAr: "الحسن التعليل", nameEn: "Al-Husn al-Ta'lil — Creative Causation", skillKey: "husan_tallil", skillDescriptionEn: "When a poet invents a beautiful fictional reason for a natural phenomenon", roleplaysScenarioAr: "أنت تشرح لطفل لماذا تبكي السماء — وتفعل ذلك شعراً", roleplaysScenarioEn: "You explain to a child why the sky weeps — and you do it in poetry", systemPrompt: "Teach حسن التعليل (al-husn al-ta'lil — beautiful causation) — when a poet invents a poetic, fictional cause for a real phenomenon. Famous example: 'The stars weep because they miss the beloved who left.' Give 3 examples. Ask the student to invent a beautiful poetic reason for: why roses are red, why the wind sighs, why the moon hides sometimes.", xpReward: 120 },
  { levelNumber: 49, nameAr: "الالتفات", nameEn: "Al-Iltifat — Sudden Address Shifts", skillKey: "iltifat", skillDescriptionEn: "The dramatic technique of suddenly shifting the person being addressed in a poem", roleplaysScenarioAr: "أنت تكتب عن غائب ثم تُخاطبه فجأة — يشعر القارئ وكأنك التفتّ إليه فجأةً", roleplaysScenarioEn: "You write about an absent person then suddenly address them directly — the reader feels the sudden turn", systemPrompt: "Teach الالتفات (iltifat) — the sudden shift from third person to second or first person within a poem. This creates dramatic emotional effect, like suddenly turning to address someone. Famous Quranic and poetic examples. Discuss why it's so powerful — it breaks the distance. Ask the student to write 3 sentences about someone in 3rd person, then dramatically shift to address them in 2nd person.", xpReward: 120 },
  { levelNumber: 50, nameAr: "الرمز والإيحاء", nameEn: "Symbol and Suggestion", skillKey: "ramz", skillDescriptionEn: "How great poets encode layers of meaning — symbolic imagery that resonates beyond its surface", roleplaysScenarioAr: "درويش يكتب عن 'الأرض' — هل يعني التراب فحسب؟ أنت ناقد تكشف الطبقات", roleplaysScenarioEn: "Darwish writes about 'the Earth' — does he only mean soil? You are a critic uncovering the layers", systemPrompt: "Teach الرمز والإيحاء (symbol and suggestion) — how great poets use concrete images to suggest larger, layered meanings. Examples: Darwish's 'olive tree' = Palestinian homeland, home, persistence; Al-Sayyab's 'rain' = death, resurrection, fertility. Analyze a Darwish stanza together. Ask: what does the 'rain' symbolize in this verse? What does the 'sea' suggest? The student chooses one symbol from nature and explains what it could represent.", xpReward: 130 },
  { levelNumber: 51, nameAr: "التناص والإشارات الشعرية", nameEn: "Intertextuality in Poetry", skillKey: "intertextuality", skillDescriptionEn: "How poets quote, echo, and respond to each other across centuries", roleplaysScenarioAr: "أنت تقرأ بيتاً لدرويش وتُدرك أنه يرد على المتنبي عبر الزمن — أي سحر هذا!", roleplaysScenarioEn: "You read a Darwish verse and realize he's responding to Al-Mutanabbi across centuries — what magic!", systemPrompt: "Teach التناص (intertextuality) — how modern poets echo, respond to, or transform classical verses. Show Darwish echoing the Mu'allaqat; Nizar Qabbani playing with Majnun Layla. Discuss how this creates a 'dialogue across time.' Find pairs of verses — classical and modern — that share an image or theme. Ask: can the student think of a modern phrase that echoes a classical poem they've learned?", xpReward: 130 },
  { levelNumber: 52, nameAr: "الطبيعة في الشعر العربي", nameEn: "Nature in Arabic Poetry", skillKey: "nature_poetry", skillDescriptionEn: "How Arab poets described the desert, the sea, the rain, and the stars", roleplaysScenarioAr: "أنت ترسم بكلمات المشهد الذي أمامك — الصحراء، والأفق، والنجوم", roleplaysScenarioEn: "You paint with words the scene before you — the desert, the horizon, the stars", systemPrompt: "Explore nature imagery in Arabic poetry: the desert (الصحراء) — its heat, loneliness, vastness; the rain (المطر) — as symbol of fertility and sadness; the sea (البحر) — power and the unknown; the night (الليل) and stars. Compare how pre-Islamic Bedouin poets describe nature vs. Andalusian garden poets vs. modern Darwish. Ask the student to describe a scene from nature in 3-5 lines of poetic prose.", xpReward: 120 },
  { levelNumber: 53, nameAr: "المرأة في الشعر العربي", nameEn: "Women in Arabic Poetry", skillKey: "women_poetry", skillDescriptionEn: "Explore the portrayal of women — as muse, as poet, as symbol — across Arabic literary history", roleplaysScenarioAr: "أنت تحضر حفلة شعرية تُنشد فيها الشاعرة وُلاّدة بنت المستكفي قصيدتها بنفسها", roleplaysScenarioEn: "You attend a poetry evening where the poetess Wallada bint al-Mustakfi recites her own poem", systemPrompt: "Explore the complex role of women in Arabic poetry: as the silent muse in most classical poetry; as poets themselves — Al-Khansa, Wallada bint al-Mustakfi (who embroidered poetry on her robes), and Layla al-Akhyaliyya. Discuss how women's voices changed in modern poetry. Share Wallada's famous self-asserting verse. Ask: has the student read or written poetry from a woman's perspective?", xpReward: 120 },
  { levelNumber: 54, nameAr: "الشعر والموسيقى", nameEn: "Poetry and Music", skillKey: "music_poetry", skillDescriptionEn: "The ancient bond between Arabic poetry and music — maqamat, tarab, and the sung poem", roleplaysScenarioAr: "أنت تستمع لأم كلثوم تُغنّي قصيدة — الكلمات والموسيقى تصبح شيئاً واحداً", roleplaysScenarioEn: "You listen to Umm Kulthum sing a poem — the words and music become one thing", systemPrompt: "Explore the inseparable bond of Arabic poetry and music. Discuss: the maqamat (مقامات — musical modes); how classical poems were sung (al-tarab الطرب); Umm Kulthum's partnership with poets like Al-Shafi'i and Ahmad Shawqi; modern-day song lyrics as poetry. Play with the idea: if the student's favorite poem were a song, what mood/genre would it be? Why does rhythm in poetry naturally invite music?", xpReward: 120 },
  { levelNumber: 55, nameAr: "المفارقة والسخرية الشعرية", nameEn: "Irony and Satire in Poetry", skillKey: "irony_satire", skillDescriptionEn: "How poets use irony, sarcasm, and wit as weapons and as art", roleplaysScenarioAr: "أنت شاعر في بلاط المأمون — تُريد أن تُوجّه نقداً لسياسة الخليفة بذكاء، بلا أن تُعاقَب", roleplaysScenarioEn: "You are a court poet under Al-Ma'mun — you want to critique the caliph's policy cleverly, without being punished", systemPrompt: "Explore irony (مفارقة) and satire (هجاء ساخر) in Arabic poetry as sophisticated art forms. Discuss how court poets had to be diplomatically clever — praising and criticizing simultaneously. Give examples of brilliant satirical verses. Role-play: the student must compose a 2-line verse that seems to praise but subtly criticizes something (the teacher plays 'the caliph' who must not notice the critique).", xpReward: 130 },
  { levelNumber: 56, nameAr: "البلاغة القرآنية وأثرها في الشعر", nameEn: "Quranic Rhetoric and its Influence", skillKey: "quranic_rhetoric", skillDescriptionEn: "How Quranic stylistic brilliance influenced and elevated all subsequent Arabic poetry", roleplaysScenarioAr: "أنت عالم لغوي في بغداد تستخرج جمال أسلوب القرآن وتُقارنه بأجمل الشعر العربي", roleplaysScenarioEn: "You are a linguist in Baghdad uncovering the beauty of Quranic style and comparing it to the finest poetry", systemPrompt: "Discuss the profound influence of Quranic style on Arabic poetry and rhetoric. The Quran's inimitability (الإعجاز) set the highest standard. Analyze rhetorical devices in Quran: التشبيه، الاستعارة، الجناس، الطباق found in Quranic verses. Discuss how scholars like Abd al-Qahir al-Jurjani built their rhetorical theory from Quranic analysis. Share one Quranic verse and analyze its linguistic beauty.", xpReward: 140 },
  { levelNumber: 57, nameAr: "الوصف في الشعر العربي", nameEn: "The Art of Description — Al-Wasf", skillKey: "wasf", skillDescriptionEn: "How Arab poets turned description into a complete art form — painting with words", roleplaysScenarioAr: "أنت شاعر عباسي تصف وليمة فاخرة — كل تفصيلة يجب أن تكون شعراً", roleplaysScenarioEn: "You are an Abbasid poet describing a lavish banquet — every detail must be poetry", systemPrompt: "Teach the tradition of الوصف (al-wasf — descriptive poetry) as a distinct genre: describing nature, palaces, horses, wine, beloved's beauty. Abu Nuwas perfected description of wine; Al-Buhturi (البحتري) described Ctesiphon palace. The challenge: can the student describe something ordinary (a cup of tea, a morning walk) using the layered, sensory techniques of the great descriptive poets?", xpReward: 130 },
  { levelNumber: 58, nameAr: "الحكمة في الشعر العربي", nameEn: "Wisdom and Philosophy in Poetry", skillKey: "hikma", skillDescriptionEn: "The noble tradition of wisdom verses — حِكَم — in Arabic poetry", roleplaysScenarioAr: "أنت تكتب حكمة ستُحفر على باب مدرسة — ماذا تقول للطلاب القادمين؟", roleplaysScenarioEn: "You write a wisdom verse to be carved on a school's gate — what do you say to the students who will enter?", systemPrompt: "Teach الحكمة (hikma — wisdom poetry) as one of the noblest traditions. Zuhair ibn Abi Sulma was the master of pre-Islamic wisdom verses. Al-Mutanabbi's philosophical wisdom verses. Al-Ma'arri's pessimistic wisdom. The student learns and reflects on 5 great wisdom verses. Then: they compose their own wisdom verse — 1-2 lines of advice, truth, or observation they genuinely believe.", xpReward: 130 },
  { levelNumber: 59, nameAr: "الشوق والغياب في الشعر", nameEn: "Longing and Absence in Poetry", skillKey: "shawq", skillDescriptionEn: "The universal poetic theme of yearning — for the beloved, the homeland, the past", roleplaysScenarioAr: "أنت في منفاك البعيد تكتب إلى وطنك الذي تركته — كل بيت يحمل وجعاً حقيقياً", roleplaysScenarioEn: "You are in distant exile writing to your homeland you left — each verse carries real pain", systemPrompt: "Explore the great theme of شوق (longing/yearning) across Arabic poetry — for the beloved (الغزل), for the homeland (الحنين إلى الوطن), for the past (الزمن الجميل). Darwish's exile poetry, Ibn Zaydun's longing for Wallada, the prisoner's longing for freedom. Guide the student: write a short poem expressing longing for something or someone real in their life — 3-5 lines of genuine feeling.", xpReward: 140 },
  { levelNumber: 60, nameAr: "اختبار المرحلة الثالثة", nameEn: "Stage 3 Final Challenge", skillKey: "stage3_review", skillDescriptionEn: "Master challenge on rhetoric, figures of speech, and literary devices", roleplaysScenarioAr: "أنت تتقدم لنيل وسام البلاغة من أكاديمية الشعر العربي — أمامك لجنة من الرقاشي والجرجاني", roleplaysScenarioEn: "You apply for the Badge of Eloquence from the Arabic Poetry Academy — before a panel of Al-Asma'i and Al-Jurjani", systemPrompt: "Stage 3 final exam. The panel presents: (1) Identify this figure of speech [simile example]; (2) Find the kinaya in this verse; (3) What is tibaq? Give an example; (4) Create a metaphor for 'time'; (5) Analyze this verse for all rhetorical devices you can find. Grade thoughtfully, celebrate progress, and open the door to Stage 4 — Analysis and Appreciation.", xpReward: 200 },

  // STAGE 4: Analysis (61-80)
  { levelNumber: 61, nameAr: "كيف تحلل قصيدة؟", nameEn: "How to Analyze a Poem", skillKey: "analysis_method", skillDescriptionEn: "A systematic method for reading, understanding, and analyzing any Arabic poem", roleplaysScenarioAr: "أنت ناقد أدبي يكتب مقالاً عن قصيدة لأول مرة — كيف تبدأ؟", roleplaysScenarioEn: "You are a literary critic writing about a poem for the first time — where do you begin?", systemPrompt: "Teach a systematic approach to poetry analysis: 1) Context (poet, era, occasion); 2) First reading — overall impression; 3) Structure (meter, rhyme, stanzas); 4) Imagery — identify all figures of speech; 5) Themes and meaning (surface + deep); 6) Emotional impact. Apply this method step by step to a short, famous poem. Ask the student to analyze one verse using this framework.", xpReward: 120 },
  { levelNumber: 62, nameAr: "تحليل معلقة امرؤ القيس كاملاً", nameEn: "Analyzing the Mu'allaqa of Imru' al-Qays", skillKey: "analysis_muallaqat1", skillDescriptionEn: "Deep analysis of the most famous Arabic poem — its structure, themes, and images", roleplaysScenarioAr: "أنت محرر في مجلة أدبية مكلّف بكتابة دراسة نقدية عن معلقة امرؤ القيس", roleplaysScenarioEn: "You are an editor at a literary journal tasked with writing a critical study of Imru' al-Qays's Mu'allaqa", systemPrompt: "In-depth analysis of Imru' al-Qays's Mu'allaqa. Walk through: the opening (الطلل — the abandoned campsite); the love section; the horse description; the storm ending. For each section: what images are used? What emotions? What meter? What does each section reveal about pre-Islamic Arab values and worldview? Quiz the student on specific images and their meanings.", xpReward: 140 },
  { levelNumber: 63, nameAr: "تحليل قصائد المتنبي", nameEn: "Analyzing Al-Mutanabbi's Great Odes", skillKey: "analysis_mutanabbi", skillDescriptionEn: "Analyze the profound philosophical and martial odes of Al-Mutanabbi", roleplaysScenarioAr: "أنت ترافق المتنبي في رحلته من حلب إلى مصر — يُملي عليك قصيدته وأنت تكتب وتُحلّل", roleplaysScenarioEn: "You travel with Al-Mutanabbi from Aleppo to Egypt — he dictates his poem and you write and analyze", systemPrompt: "Deep dive into Al-Mutanabbi's major poems. Analyze: the famous 'واحرّ قلباه' — written in anger at Saif al-Dawla; his self-praise odes; his wisdom verses. For each: what is the context? What rhetorical devices? What meter? What is the emotional peak? Discuss his ego, philosophy, and the tension between his greatness and arrogance. Quiz: match verses to their contexts.", xpReward: 140 },
  { levelNumber: 64, nameAr: "قصيدة البردة — البوصيري", nameEn: "The Burda — Al-Busiri's Masterpiece", skillKey: "analysis_burda", skillDescriptionEn: "Analyze the most beloved religious poem in Islam — the Prophet's ode by Al-Busiri", roleplaysScenarioAr: "أنت تتلو البردة في مسجد قديم — وتشعر بأثرها الروحي على كل من حولك", roleplaysScenarioEn: "You recite the Burda in an ancient mosque — feeling its spiritual effect on everyone around you", systemPrompt: "Analyze the Burda (البردة) by Al-Busiri — the most beloved religious poem in Arabic, praising the Prophet Muhammad ﷺ. Teach: the historical context (Al-Busiri's paralysis cured after a dream vision of the Prophet); its structure; its famous opening (أمن تذكّر جيرانٍ بذي سلم); the themes of love, repentance, praise, and intercession. Discuss why it's still recited worldwide 700 years later.", xpReward: 130 },
  { levelNumber: 65, nameAr: "تحليل ديوان درويش", nameEn: "Analyzing Darwish's Divan", skillKey: "analysis_darwish", skillDescriptionEn: "Close reading of Mahmoud Darwish's most powerful poems", roleplaysScenarioAr: "أنت في غرفة درويش بعد رحيله — تقرأ آخر ديوان كتبه وتحاول فهم ما أراد قوله", roleplaysScenarioEn: "You are in Darwish's room after his passing — reading his last collection, trying to understand what he wanted to say", systemPrompt: "Deep reading of Darwish's major poems: 'على هذه الأرض ما يستحق الحياة', 'لاعب النرد' (The Dice Player — his final poem), 'عابرون في كلام عابر'. For each: imagery analysis, theme, emotional arc. What does 'the Earth' mean? What does 'the sea' mean in his poetry? Discuss his shift from political to existential/philosophical poetry in his late career.", xpReward: 150 },
  { levelNumber: 66, nameAr: "الشعر في السياق التاريخي", nameEn: "Poetry in Historical Context", skillKey: "historical_context", skillDescriptionEn: "How to read a poem as a historical document — what it tells us about its time", roleplaysScenarioAr: "أنت مؤرخ تستخدم الشعر مصدراً أولياً لفهم ما جرى في معركة القادسية", roleplaysScenarioEn: "You are a historian using poetry as a primary source to understand what happened at the Battle of Qadisiyya", systemPrompt: "Teach reading poetry as a historical document. How do pre-Islamic poems reveal Bedouin life? How do Umayyad court odes reveal the political structure? How does Abbasid wine poetry reveal the cosmopolitan culture of Baghdad? Analyze a specific poem and extract 5 historical facts from it. Then ask: what does Nizar Qabbani's poem after 1967 tell us about the Arab world at that moment?", xpReward: 140 },
  { levelNumber: 67, nameAr: "المقارنة بين الشعراء", nameEn: "Comparing Poets Across Eras", skillKey: "comparative_poetry", skillDescriptionEn: "Compare how different poets treated the same theme — love, death, nature, God", roleplaysScenarioAr: "أنت محكّم في مسابقة: من وصف الليل أجمل — المتنبي أم درويش؟", roleplaysScenarioEn: "You are a judge in a competition: who described the night more beautifully — Al-Mutanabbi or Darwish?", systemPrompt: "Comparative analysis: present pairs of poems on the same theme from different eras. Theme of night: Al-Mutanabbi vs. Darwish. Theme of death: Al-Khansa vs. Darwish. Theme of love: Qays Majnun vs. Nizar Qabbani. For each pair: what similarities? What differences? What does the difference reveal about the era and the poet's personality? The student decides who 'wins' each comparison and defends their choice.", xpReward: 140 },
  { levelNumber: 68, nameAr: "الشعر والهوية", nameEn: "Poetry and Identity", skillKey: "poetry_identity", skillDescriptionEn: "How Arabic poetry shaped and expressed Arab identity — tribal, religious, national, personal", roleplaysScenarioAr: "أنت تُحدّد نفسك بشعر — أيّ بيت يُعبّر عنك أكثر من أي تعريف آخر؟", roleplaysScenarioEn: "You define yourself through poetry — which verse expresses you better than any other description?", systemPrompt: "Explore poetry as identity formation: how pre-Islamic poetry encoded tribal identity; Islamice poetry encoded religious identity; modern poetry encoded national identity (Darwish — Palestinian; Nizar — Arab modernist). Ask the student: which poem or verse resonates most with your identity? Have them explain why. Then guide them to write one verse that captures something essential about who they are.", xpReward: 140 },
  { levelNumber: 69, nameAr: "النقد الأدبي الكلاسيكي", nameEn: "Classical Arabic Literary Criticism", skillKey: "literary_criticism", skillDescriptionEn: "The great tradition of Arabic critics — Al-Amidi, Ibn Qutaybah, and their poetic debates", roleplaysScenarioAr: "أنت تحضر مجلس المفاضلة بين المتنبي وأبي تمام — أيّهما أشعر؟", roleplaysScenarioEn: "You attend the debate: who is the greater poet — Al-Mutanabbi or Abu Tammam?", systemPrompt: "Introduce classical Arabic literary criticism. Key figures: Ibn Qutayba (ابن قتيبة), al-Amidi (الآمدي) who compared Abu Tammam and Al-Buhturi, al-Jurjani (الجرجاني) who analyzed the 'secret of eloquence.' The famous debate: is it better when poetry is clear and natural, or obscure and complex? Role-play the Mutanabbi vs. Abu Tammam debate — the student argues for one, the teacher the other.", xpReward: 150 },
  { levelNumber: 70, nameAr: "قراءة الشعر بصوت عالٍ", nameEn: "Reading Poetry Aloud — The Art of Inshad", skillKey: "inshad", skillDescriptionEn: "The tradition of إنشاد — reciting poetry with proper voice, breath, emotion, and rhythm", roleplaysScenarioAr: "أنت مُنشد شعر في أمسية ثقافية — الجمهور ينتظر ومنك أن تجعله يشعر بكل كلمة", roleplaysScenarioEn: "You are a poetry reciter at a cultural evening — the audience waits and you must make them feel every word", systemPrompt: "Teach the art of إنشاد (inshad — poetry recitation). Principles: breath control, honoring the meter with rhythm, emotional authenticity, pausing at the right moments, letting silences speak. Discuss how great poetry readers (like Umm Kulthum, or in readings by Darwish himself) transform a poem. Practice: the teacher recites a verse; the student recites it back. Provide feedback on rhythm, emotion, and pacing.", xpReward: 140 },
  { levelNumber: 71, nameAr: "الشعر في حياتنا اليومية", nameEn: "Poetry in Daily Life", skillKey: "poetry_daily", skillDescriptionEn: "How Arabic poetry permeates speech, proverbs, songs, and everyday Arab culture", roleplaysScenarioAr: "أنت في حفل زفاف — الجد يُنشد بيتاً من الشعر في كلمته — والكل يفهم رمزه", roleplaysScenarioEn: "You are at a wedding — the grandfather recites a verse of poetry in his speech — everyone understands its symbol", systemPrompt: "Explore how Arabic poetry lives in daily life: common Arabic proverbs that are actually verses of poetry; how poetry appears in speeches, weddings, funerals, political rallies; song lyrics as poetry; children's nursery rhymes in Arabic. Ask the student: have they heard a verse of poetry outside a classroom? In a song? In a family gathering? Share examples from their culture. This connects their learning to real life.", xpReward: 120 },
  { levelNumber: 72, nameAr: "الشعر والسياسة", nameEn: "Poetry and Politics", skillKey: "poetry_politics", skillDescriptionEn: "How Arabic poetry served as resistance, propaganda, protest, and revolution", roleplaysScenarioAr: "أنت شاعر في الثورة العربية — قصيدتك قد تُلهم الجماهير أو قد تُودي بك إلى السجن", roleplaysScenarioEn: "You are a poet during the Arab revolution — your poem may inspire the masses or land you in prison", systemPrompt: "Explore the political power of Arabic poetry: Hassan ibn Thabit defending Islam; Abbasid poets critiquing sultans under cover; Nizar Qabbani's 'Marginal Notes on the Book of Defeat' after 1967 — the most politically explosive Arabic poem of the 20th century; revolutionary poets of 2011. Ask: can poetry change politics? Give examples. Ask the student to write a short political verse about something in the world that troubles them.", xpReward: 150 },
  { levelNumber: 73, nameAr: "الشعر والصوفية", nameEn: "Sufi Poetry — Poetry of the Soul", skillKey: "sufi_poetry", skillDescriptionEn: "The mystical tradition — Rumi, Ibn Arabi, Al-Hallaj — poetry as a path to the divine", roleplaysScenarioAr: "أنت في حلقة ذكر — الدراويش يدورون والشعر يُنشد حتى يذوب الحد بين العالمين", roleplaysScenarioEn: "You are in a Sufi dhikr circle — the dervishes spin and poetry is chanted until the boundary between worlds dissolves", systemPrompt: "Introduce Sufi mystical poetry in Arabic: al-Hallaj (الحلاج) and his ecstatic verses (including the famous 'أنا الحق'); Ibn Arabi (ابن عربي) and his 'Tarjuman al-Ashwaq'; discuss how Sufi poets used the language of love poetry to speak of divine love — deliberately ambiguous whether 'the beloved' is human or divine. Explore the tradition of sama' (السماع) — listening to poetry as spiritual practice.", xpReward: 150 },
  { levelNumber: 74, nameAr: "مقارنة الشعر العربي بالشعر العالمي", nameEn: "Arabic Poetry and World Poetry", skillKey: "world_comparison", skillDescriptionEn: "Compare Arabic poetic traditions with Greek, Persian, English, and Japanese poetry", roleplaysScenarioAr: "أنت في مؤتمر شعري دولي — تُقدّم الشعر العربي للعالم بكلمات بسيطة ومثيرة", roleplaysScenarioEn: "You are at an international poetry conference — introducing Arabic poetry to the world with simple, exciting words", systemPrompt: "Comparative world poetry: Compare Arabic qasida structure with Greek ode, Shakespeare's sonnet, Persian ghazal, Japanese haiku. What does each tradition uniquely value? How did Arabic poetry influence Persian poetry (and vice versa)? How did Andalusian Arabic influence European troubadour poetry? The student: pick one non-Arabic poem they know and find parallels with an Arabic poem.", xpReward: 150 },
  { levelNumber: 75, nameAr: "الشعر الرقمي والعصر الحديث", nameEn: "Digital Poetry and the Modern Age", skillKey: "digital_poetry", skillDescriptionEn: "Arabic poetry in the age of social media, Instagram poetry, and digital platforms", roleplaysScenarioAr: "أنت شاعر يكتب قصيدته على تويتر — 140 حرفاً تحمل كل شيء أو لا تحمل شيئاً", roleplaysScenarioEn: "You are a poet writing your poem on Twitter — 140 characters that carry everything or nothing", systemPrompt: "Discuss Arabic poetry in the digital age: Instagram poets, Twitter poetry, the democratization of poetry. Is a popular Instagram poem with 1 million likes 'great poetry'? Debate: has social media helped or hurt poetry? Discuss how young Arab poets are finding new audiences. The student: write a poem short enough to fit in a tweet (280 characters) but meaningful. This is the hardest form — brevity + depth.", xpReward: 130 },
  { levelNumber: 76, nameAr: "أشعار الأطفال", nameEn: "Children's Poetry in Arabic", skillKey: "children_poetry", skillDescriptionEn: "The beautiful world of Arabic nursery rhymes, songs, and children's verse", roleplaysScenarioAr: "أنت تُعلّم طفلاً صغيراً أول قصيدة في حياته — ماذا تختار؟ وكيف تجعله يُحبّها؟", roleplaysScenarioEn: "You are teaching a young child their first poem ever — what do you choose? How do you make them love it?", systemPrompt: "Explore Arabic children's poetry — nursery rhymes, school poems, traditional lullabies. Discuss how children first learn language through poetry's rhythm and rhyme. Teach the student a famous short Arabic children's verse. Then challenge: write a short, simple poem that a 6-year-old child could understand, enjoy, and remember. It must rhyme and have a clear, happy message.", xpReward: 120 },
  { levelNumber: 77, nameAr: "الكتابة الإبداعية: الملاحظة والتحويل", nameEn: "Creative Writing: Observation to Poetry", skillKey: "observation_writing", skillDescriptionEn: "The poet's eye — how to observe ordinary things and transform them into extraordinary poetry", roleplaysScenarioAr: "أنت تجلس في مقهى — كوب قهوة، رجل يقرأ، وطفلة تنظر من النافذة — هذا كل ما تحتاجه لقصيدة", roleplaysScenarioEn: "You sit in a café — a cup of coffee, a man reading, a girl looking through the window — this is all you need for a poem", systemPrompt: "Teach the fundamental craft of observation-to-poetry. Like Chekhov's gun in prose, in poetry every detail matters. Exercise: describe a simple scene in front of you (real or imagined) — 5 ordinary details. Now, the teacher guides the student to transform each ordinary detail into a poetic image using what they've learned: simile, metaphor, kinaya. By the end, a mundane scene becomes a poem.", xpReward: 140 },
  { levelNumber: 78, nameAr: "الشعر والذاكرة", nameEn: "Poetry and Memory", skillKey: "poetry_memory", skillDescriptionEn: "How poetry preserves memory — personal, cultural, and historical — across generations", roleplaysScenarioAr: "أنت تستحضر ذكرى جدّتك التي ماتت — والشعر يمنحك طريقة لتجعلها حاضرة للأبد", roleplaysScenarioEn: "You invoke the memory of your grandmother who passed away — and poetry gives you a way to make her present forever", systemPrompt: "Explore memory in Arabic poetry — the 'nasib' (نسيب) as memory of the beloved; رثاء as preservation of the dead; Darwish's exile poetry as cultural memory. How does writing a poem about someone keep them alive? Ask the student to write 3-5 lines in memory of someone or something they have lost — a person, a place, a time of life. Guide them to use one concrete sensory image.", xpReward: 150 },
  { levelNumber: 79, nameAr: "القراءة النقدية المتقدمة", nameEn: "Advanced Critical Reading", skillKey: "advanced_analysis", skillDescriptionEn: "Read a poem against the grain — subtext, silences, what the poet doesn't say", roleplaysScenarioAr: "أنت تقرأ قصيدة وتُدرك أن ما لم يُقَل فيها أهمّ مما قيل — اقرأ الصمت", roleplaysScenarioEn: "You read a poem and realize what was NOT said is more important than what was — read the silence", systemPrompt: "Advanced literary analysis: reading the subtext — what the poem doesn't say but implies; the cultural assumptions the poet relies on without stating; the gender, class, or political biases embedded in language. Take a famous poem (suggest Al-Mutanabbi's self-praise or a Darwish poem) and read it 'against the grain.' What is the poet NOT telling us? What does this reveal? This is the most challenging analytical exercise.", xpReward: 160 },
  { levelNumber: 80, nameAr: "اختبار المرحلة الرابعة", nameEn: "Stage 4 Final Challenge", skillKey: "stage4_review", skillDescriptionEn: "Full analysis of an unseen poem — applying all critical and analytical tools learned", roleplaysScenarioAr: "أنت تتقدم لمنح جائزة دراسات الشعر — أمامك قصيدة لم تقرأها من قبل، وخمس دقائق للتحليل", roleplaysScenarioEn: "You apply for a poetry studies prize — before you is a poem you've never read, and five minutes to analyze it", systemPrompt: "Stage 4 final exam: Present the student with a short, complete poem they haven't seen before (choose one by Ibn Khafaja or a lesser-known Abbasid poet). Ask them to apply the full analysis method: (1) Context guess; (2) Meter identification; (3) Identify 3 rhetorical devices; (4) Main theme; (5) Your personal response. Celebrate their analysis and open the door to Stage 5 — Composition and Creativity.", xpReward: 200 },

  // STAGE 5: Composition (81-100)
  { levelNumber: 81, nameAr: "من القارئ إلى الشاعر", nameEn: "From Reader to Poet", skillKey: "reader_to_poet", skillDescriptionEn: "The mindset shift — from analyzing others' poetry to creating your own", roleplaysScenarioAr: "أنت تُمسك بالقلم لأول مرة كشاعر — لا كطالب — وتشعر بثقل اللحظة", roleplaysScenarioEn: "You pick up the pen for the first time as a POET — not a student — and feel the weight of the moment", systemPrompt: "This is the transition from reader to creator. Discuss the psychological shift: from analysis (what did the poet mean?) to creation (what do I mean?). Address the fear of the blank page. Discuss how all great poets began by imitating — and this is not copying, it's learning. Exercise: pick a poem the student loves and write a verse 'in the style of' that poet on a theme the student chooses.", xpReward: 150 },
  { levelNumber: 82, nameAr: "كتابة بيت واحد", nameEn: "Writing One Perfect Verse", skillKey: "writing_one_verse", skillDescriptionEn: "The fundamental unit — crafting a single verse that stands alone with power and beauty", roleplaysScenarioAr: "المعلم يُعطيك صورة — سماء ليلية — وعليك أن تكتب البيت الوحيد الذي يصفها بشكل لم يُوصف به من قبل", roleplaysScenarioEn: "The teacher gives you an image — a night sky — you must write the single verse that describes it as never before", systemPrompt: "The core workshop: writing one perfect verse. Principles: (1) start with a concrete image; (2) use one comparison; (3) make the sounds serve the meaning; (4) revise until every word is necessary. Present 3 images: a night sky, an empty chair, hands of an old person. For each, the student writes one verse. Teacher provides detailed feedback on each one: what works, what can be improved, what to try differently.", xpReward: 150 },
  { levelNumber: 83, nameAr: "كتابة على بحر الطويل", nameEn: "Writing in Al-Tawil Meter", skillKey: "composing_tawil", skillDescriptionEn: "Compose your own verses in the most classic Arabic meter — Al-Tawil", roleplaysScenarioAr: "أنت تكتب قصيدة بالطويل وكأنك جاهلي يصف صحراءه — المعلم يُصحّح الوزن بلطف", roleplaysScenarioEn: "You write a poem in Al-Tawil as if you were a Jāhilī poet describing his desert — the teacher gently corrects the meter", systemPrompt: "Composition practice in Al-Tawil meter. Step 1: teacher demonstrates the scansion of Tawil again. Step 2: student writes ONE verse in Tawil on any topic — it can be imperfect. Step 3: teacher scans what the student wrote, identifies what's right and what needs adjustment. Step 4: revise together. Goal: the student has one correct verse in Tawil that they wrote themselves by the end. Celebrate the achievement.", xpReward: 160 },
  { levelNumber: 84, nameAr: "كتابة على بحر الكامل", nameEn: "Writing in Al-Kamil Meter", skillKey: "composing_kamil", skillDescriptionEn: "Compose your own verses in Al-Kamil — the meter of Al-Mutanabbi", roleplaysScenarioAr: "أنت تتخيل أنك المتنبي — تكتب بيتاً بالكامل يُعبّر عن عزمك وإرادتك", roleplaysScenarioEn: "Imagine you are Al-Mutanabbi — write a verse in Al-Kamil expressing your determination and will", systemPrompt: "Composition practice in Al-Kamil meter. The student writes a martial/personal power verse 'as Al-Mutanabbi would.' Teacher demonstrates the متفاعلن pattern. Student writes one verse. Teacher scans and corrects together. Importantly: help the student feel the pride and power that Kamil conveys — the writing must come from real feeling. By end: one corrected verse in Kamil.", xpReward: 160 },
  { levelNumber: 85, nameAr: "كتابة قصيدة قصيرة متكاملة", nameEn: "Writing a Complete Short Poem", skillKey: "complete_poem", skillDescriptionEn: "Combine verses into a coherent whole — a short poem with opening, development, and close", roleplaysScenarioAr: "تكتب قصيدتك الأولى المتكاملة — ثلاثة أبيات فقط، لكنّها لك وحدك", roleplaysScenarioEn: "You write your first complete poem — just three verses, but they are entirely yours", systemPrompt: "Guide the student through writing a complete short poem: 3-5 verses. Structure: (1) Opening verse — introduce the scene or emotion; (2) Middle verse(s) — develop the image or idea; (3) Closing verse — a twist, a conclusion, or a question left open. The student chooses their own topic. Teacher provides structure guidance and detailed feedback on each draft. Celebrate the completed poem — this is a milestone.", xpReward: 180 },
  { levelNumber: 86, nameAr: "التنقيح والمراجعة الشعرية", nameEn: "Revision — The Poet's Real Work", skillKey: "revision", skillDescriptionEn: "Great poems are rewritten, not written — the art of revision and refinement", roleplaysScenarioAr: "أنت تنظر إلى قصيدتك بعيون ناقد — وتقرر: ما الذي يجب أن يحيا وما الذي يجب أن يُحذف؟", roleplaysScenarioEn: "You look at your poem with a critic's eyes — deciding: what must live and what must be cut?", systemPrompt: "Teach revision as a craft: 'Kill your darlings.' Take the student's poem from Level 85. Ask: Is every word necessary? Is the comparison fresh? Does the ending land? Could one word be stronger? Practice three rounds of revision on one of their verses: (1) cut unnecessary words; (2) replace the weakest word; (3) strengthen the last line. Show before-and-after to demonstrate how revision improves poetry.", xpReward: 170 },
  { levelNumber: 87, nameAr: "الإلهام والكتابة الحرة", nameEn: "Inspiration and Free Writing", skillKey: "free_writing", skillDescriptionEn: "Unlock the subconscious — free writing techniques to generate raw poetic material", roleplaysScenarioAr: "المعلم يُعطيك كلمة واحدة: 'الموج' — اكتب لمدة 5 دقائق بلا توقف وبلا رقابة", roleplaysScenarioEn: "The teacher gives you one word: 'the wave' — write for 5 minutes without stopping and without censoring yourself", systemPrompt: "Free writing exercise to unlock creative flow. Step 1: Teacher gives a single word or image. Step 2: Student writes freely for 5 minutes without stopping or self-censoring. Step 3: Student shares what they wrote. Step 4: Teacher helps identify the 'gold' — the most interesting phrase or image buried in the free write. Step 5: Develop that gem into a polished verse. This is how many poets begin — finding the poem inside the chaos.", xpReward: 160 },
  { levelNumber: 88, nameAr: "محاكاة الشعراء العظماء", nameEn: "Imitating the Greats", skillKey: "imitation", skillDescriptionEn: "Write in the style of Al-Mutanabbi, Darwish, and Nizar Qabbani — imitation as mastery", roleplaysScenarioAr: "اليوم أنت المتنبي. غداً أنت درويش. بعد غداً أنت نزار. اكتشف ما يختلف في صوتك عن كل منهم", roleplaysScenarioEn: "Today you are Al-Mutanabbi. Tomorrow Darwish. After that Nizar. Discover what in your voice differs from each", systemPrompt: "Structured imitation exercise — the highest form of learning. Three exercises: (1) Write 2 lines in Al-Mutanabbi's style: proud, assertive, philosophical, with heavy rhetoric; (2) Write 2 lines in Darwish's style: lyrical, land-focused, image-driven, modern; (3) Write 2 lines in Nizar's style: direct, emotional, about love or politics. After all three: where does the student's natural voice feel most comfortable? That is their style to develop.", xpReward: 180 },
  { levelNumber: 89, nameAr: "كتابة القصيدة الشخصية", nameEn: "Writing the Personal Poem", skillKey: "personal_poem", skillDescriptionEn: "The hardest and most important poem — about yourself, your life, your truth", roleplaysScenarioAr: "الآن — بلا دروع، بلا أقنعة — اكتب القصيدة التي لم تجرؤ على كتابتها حتى الآن", roleplaysScenarioEn: "Now — without armor, without masks — write the poem you haven't dared to write until now", systemPrompt: "The most personal assignment: the student writes a poem that is genuinely about their own life, experience, feeling, or truth. No imitation, no performance — just their authentic voice. Teacher creates a safe space. Give prompts if needed: write about a place that shaped you; a relationship that changed you; a fear you carry; something you've never said out loud. Offer only encouragement and one question after reading: 'is this really what you meant?'", xpReward: 200 },
  { levelNumber: 90, nameAr: "ديوان المتعلم الأول", nameEn: "The Student's First Divan", skillKey: "first_divan", skillDescriptionEn: "Collect and curate your best poems into a small personal collection", roleplaysScenarioAr: "أنت تُعدّ ديوانك الأول — تختار القصائد وتُرتّبها وتُسمّيها واحدة واحدة", roleplaysScenarioEn: "You are preparing your first divan — selecting, ordering, and naming your poems one by one", systemPrompt: "This level is about curation: the student has now written multiple poems across the previous levels. Guide them to collect their best work, revise one more time, and arrange them into a small 'divan' (even if just 3-5 poems). They should: title each poem, decide the order (thematic? emotional arc?), write a short introduction to their collection. Celebrate: this is a real, personal collection of their own Arabic poetry.", xpReward: 200 },
  { levelNumber: 91, nameAr: "الارتجال الشعري", nameEn: "Improvised Poetry", skillKey: "improvisation", skillDescriptionEn: "The highest Arab poetic art — composing poetry instantly, in the moment, on demand", roleplaysScenarioAr: "الجمهور يصرخ موضوعاً — وعليك أن تُنشد بيتاً ارتجالياً في ثوانٍ كالشعراء القدامى", roleplaysScenarioEn: "The audience shouts a topic — and you must improvise a verse in seconds like the ancient poets", systemPrompt: "Teach and practice poetic improvisation (الارتجال) — one of the most celebrated Arab poetic arts. Famous improvisers like Al-Ma'arri, who could compose on any topic instantly. Practice drill: teacher names a topic, student has 60 seconds to compose one line. Three rounds: (1) easy topic (coffee), (2) medium (friendship), (3) challenging (time passing). No pressure for perfection — only for genuine attempt. Celebrate each attempt.", xpReward: 200 },
  { levelNumber: 92, nameAr: "الشعر بالعامية", nameEn: "Writing in Your Dialect", skillKey: "dialect_poetry", skillDescriptionEn: "Experiment with writing poetry in your own spoken dialect — it's still poetry!", roleplaysScenarioAr: "أنت تكتب قصيدة يفهمها جدّتك بلهجتها — لأن الشعر الحقيقي يصل إلى كل قلب", roleplaysScenarioEn: "You write a poem your grandmother understands in her dialect — because real poetry reaches every heart", systemPrompt: "Affirm the validity of dialect poetry. Many of the most beloved modern poems are in colloquial Arabic (Egyptian, Levantine, Moroccan, Gulf). Exercise: the student writes 3 lines in their own spoken dialect — no rules, no classical grammar requirements. Discuss: what words in their dialect are uniquely poetic and can't be translated to formal Arabic? Celebrate the richness of Arabic dialect diversity.", xpReward: 170 },
  { levelNumber: 93, nameAr: "الحوار الشعري — المناظرة", nameEn: "Poetic Dialogue — Al-Munazara", skillKey: "poetic_dialogue", skillDescriptionEn: "Write poetry as a conversation — alternating verses with a partner or imagined voice", roleplaysScenarioAr: "أنت تكتب لقصيدة — والمعلم يُجيبك ببيت — وهكذا حتى تكتملا قصيدة واحدة معاً", roleplaysScenarioEn: "You write a verse — the teacher responds with one — and so on until you complete one poem together", systemPrompt: "Poetic dialogue (المناظرة) — the tradition of poets responding to each other in verse. Practice: teacher writes an opening verse; student responds in the next; teacher responds; continue for 6-8 exchanges. The resulting poem is a genuine collaborative creation. Reflect: how did the student's verse change to respond to the teacher's? What did they discover about their voice in dialogue?", xpReward: 200 },
  { levelNumber: 94, nameAr: "نشر الشعر ومشاركته", nameEn: "Sharing and Publishing Your Poetry", skillKey: "sharing_poetry", skillDescriptionEn: "How to share your poetry with the world — readings, publications, social media", roleplaysScenarioAr: "أنت في أمسيتك الشعرية الأولى — الناس ينتظرون — هل أنت مستعد؟", roleplaysScenarioEn: "You are at your first poetry reading — people are waiting — are you ready?", systemPrompt: "Practical discussion: how do poets share their work today? Open mic nights (أمسيات شعرية); literary magazines; Instagram and social media poetry; self-publishing; poetry competitions; poetry prizes (Arab World — including the Sharjah International Book Fair poetry competitions). Role-play: the student prepares to read one of their own poems aloud. They practice with the teacher: pace, breath, emotion. A mini performance in the safe space of this lesson.", xpReward: 200 },
  { levelNumber: 95, nameAr: "الشاعر والمجتمع", nameEn: "The Poet and Society", skillKey: "poet_society", skillDescriptionEn: "What is the poet's responsibility — to beauty, to truth, to politics, to their community?", roleplaysScenarioAr: "أنت الشاعر الرسمي لمدينتك — ماذا تكتب في أزمة؟ وماذا في وقت الفرح؟", roleplaysScenarioEn: "You are the official poet of your city — what do you write in a crisis? And in times of joy?", systemPrompt: "Philosophical discussion: what is the role of the poet in society? Three views: (1) The pure aesthete — beauty is the only obligation; (2) The committed poet — poetry must serve the people; (3) The witness — the poet observes and records without judgment. Who is right? Discuss Al-Mutanabbi (court poet), Nizar Qabbani (committed political), Darwish (witness and resistance). Where does the student place themselves as a poet?", xpReward: 200 },
  { levelNumber: 96, nameAr: "تحديات الكتابة المتقدمة", nameEn: "Advanced Writing Challenges", skillKey: "advanced_challenges", skillDescriptionEn: "Push your craft to the limit with demanding formal and thematic constraints", roleplaysScenarioAr: "التحدي: اكتب قصيدة بقافية الراء، على بحر الكامل، عن الزمن — في عشر دقائق", roleplaysScenarioEn: "The challenge: write a poem with ra' rhyme, in Al-Kamil meter, about time — in ten minutes", systemPrompt: "Master-level craft challenges: (1) Write a verse using ALL FIVE rhetorical devices learned: tashbih, isti'ara, kinaya, tibaq, jinas — in one verse! (2) Write a verse where the last word of each hemistich is the same word with different meaning (perfect jinas); (3) Write a qit'a of 4 verses alternating between two meters. The teacher gives feedback on each attempt. These challenges separate competent poets from masters.", xpReward: 220 },
  { levelNumber: 97, nameAr: "قصيدة في مدح شخص تحبّه", nameEn: "A Praise Poem for Someone You Love", skillKey: "madh_personal", skillDescriptionEn: "The classical madh genre made personal — write a genuine ode to someone important in your life", roleplaysScenarioAr: "اكتب قصيدة مدح حقيقية لشخص تحبّه — أمّك، صديقك، معلمك — اجعلها هديةً لا تُنسى", roleplaysScenarioEn: "Write a genuine praise poem for someone you love — your mother, friend, teacher — make it an unforgettable gift", systemPrompt: "The personal madh (praise ode): the student writes a genuine poem praising someone real in their life. Guidance: be specific (avoid clichés — 'she is beautiful' is weaker than 'her laugh makes me believe morning comes on purpose'). Use at least one simile or metaphor. Let the emotion be real. Teacher gives feedback focused on authenticity and craft. The poem should be something the student could actually give to that person.", xpReward: 220 },
  { levelNumber: 98, nameAr: "قصيدة رثاء شخصية", nameEn: "A Personal Elegy", skillKey: "ritha_personal", skillDescriptionEn: "Write an elegy for someone or something you have lost — the hardest and most sacred form", roleplaysScenarioAr: "أنت الخنساء اليوم — تكتب رثاءً لمن أحببت — والقلم يثقل في يدك", roleplaysScenarioEn: "You are Al-Khansa today — writing an elegy for someone you loved — the pen heavy in your hand", systemPrompt: "The elegy — the hardest, most honest poem. The student writes a personal elegy for someone or something they have lost (a person, a childhood, a place, a version of themselves). Guidance: the elegy must honor specifically — not 'I miss you' but a specific memory, detail, quality. It can be angry, not just sad. Use direct address (iltifat) to speak to the absent person. Teacher creates maximum emotional safety. This poem is a gift to the student themselves.", xpReward: 250 },
  { levelNumber: 99, nameAr: "القصيدة الكبرى", nameEn: "The Major Poem", skillKey: "major_poem", skillDescriptionEn: "A complete, polished, multi-verse poem on a significant theme — your masterwork", roleplaysScenarioAr: "أنت تكتب القصيدة التي ستُعرّفك — القصيدة التي ستبقى — والمعلم يجلس إلى جانبك", roleplaysScenarioEn: "You write the poem that will define you — the poem that will endure — and the teacher sits beside you", systemPrompt: "The capstone poem: the student writes a complete, polished poem of 6-10 verses on a theme of their choice. This should represent everything they've learned: consistent meter (or deliberate free verse), rich imagery, rhetorical devices, authentic emotion, strong opening and closing. Teacher provides detailed line-by-line feedback in two rounds. Celebrate every element that works. This poem is the student's masterwork.", xpReward: 300 },
  { levelNumber: 100, nameAr: "وصلت إلى مئة — أنت شاعر", nameEn: "Level 100 — You Are a Poet", skillKey: "graduation", skillDescriptionEn: "The final celebration — you have completed the journey from zero to Arabic poet", roleplaysScenarioAr: "الكبار كلهم حاضرون — المتنبي وامرؤ القيس ودرويش ونزار — يُصفّقون لك وأنت تُنشد قصيدتك الكبرى", roleplaysScenarioEn: "All the greats are present — Al-Mutanabbi, Imru' al-Qays, Darwish, and Nizar — they applaud as you recite your major poem", systemPrompt: "GRADUATION: The final session. Role-play: all the poets studied — Al-Mutanabbi, Imru' al-Qays, Mahmoud Darwish, Nizar Qabbani, Al-Khansa, Abu Nuwas — are present in an imaginary hall to witness the student's graduation. The student recites their major poem from Level 99. Each poet in the imaginary hall offers one line of praise and encouragement. The teacher then gives a genuine, personal reflection on the student's journey, growth, and unique poetic voice. They are now a poet.", xpReward: 500 },
];

async function seed() {
  console.log("Seeding stages and levels...");

  await db.delete(stages);

  const insertedStages = await db.insert(stages).values(stagesData).returning();
  console.log(`Inserted ${insertedStages.length} stages`);

  const stageMap: Record<number, number> = {};
  for (const stage of insertedStages) {
    stageMap[stage.order] = stage.id;
  }

  const levelsWithStageIds = levelsData.map((level) => {
    let stageOrder = 1;
    if (level.levelNumber >= 21 && level.levelNumber <= 40) stageOrder = 2;
    else if (level.levelNumber >= 41 && level.levelNumber <= 60) stageOrder = 3;
    else if (level.levelNumber >= 61 && level.levelNumber <= 80) stageOrder = 4;
    else if (level.levelNumber >= 81) stageOrder = 5;

    return { ...level, stageId: stageMap[stageOrder] };
  });

  await db.insert(levels).values(levelsWithStageIds);
  console.log(`Inserted ${levelsData.length} levels`);

  const existingProgress = await db.select().from(userProgress);
  if (existingProgress.length === 0) {
    await db.insert(userProgress).values({ currentLevel: 1, totalXp: 0, completedLevels: "[]" });
    console.log("Created initial user progress");
  }

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
